MVC_Week2_HK/Controllers/CustomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_Week1_HK.Models;
using MVC_Week1_HK.ActionFilter;
using MVC_Week1_HK.Models.viewModel;
using OfficeOpenXml;

namespace MVC_Week1_HK.Controllers
{
    public class CustomController : BaseController
    {
        private 客戶資料Repository CustomRepos = RepositoryHelper.Get客戶資料Repository();

        // GET: Custom
        public ActionResult Index()
        {
            return View(CustomRepos.All().ToList());
        }

        // GET: Custom/Details/5
        [IDFilter]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = CustomRepos.Find(p=>p.Id==id.Value);
        
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.Bank = RepositoryHelper.Get客戶銀行資訊Repository().All().Where(p => p.客戶Id == id.Value).ToList();
                ViewBag.Contact = RepositoryHelper.Get客戶聯絡人Repository().All().Where(p => p.客戶Id == id.Value).ToList();
            }
            return View(客戶資料);
        }

        // GET: Custom/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Custom/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        public ActionResult Create(FormCollection form)
        {
            客戶資料 客戶資料=new 客戶資料();
            if (this.TryUpdateModel<I客戶資料Data>(客戶資料))
            {
             //   db.客戶資料.Add(客戶資料);
               // db.SaveChanges();
                CustomRepos.Add(客戶資料);
                CustomRepos.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            return View(客戶資料);
        }

        // GET: Custom/Edit/5
        [IDFilter]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomRepos.UnitOfWork.LazyLoadingEnabled = false;
            客戶資料 客戶資料 = CustomRepos.Find(p => p.Id == id.Value);
           
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.Bank = RepositoryHelper.Get客戶銀行資訊Repository().All().Where(p => p.客戶Id == id.Value).ToList();
                ViewBag.Contact = RepositoryHelper.Get客戶聯絡人Repository().All().Where(p => p.客戶Id == id.Value).ToList();
            }
            return View(客戶資料);
        }

        // POST: Custom/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormCollection form)
        {
            客戶資料 客戶資料 = new 客戶資料();
            if (this.TryUpdateModel<I客戶資料Data>(客戶資料))
            {
                this.CustomRepos.Edit(客戶資料);
                
                return RedirectToAction("Index");
            }
            ViewBag.Bank = RepositoryHelper.Get客戶銀行資訊Repository().All().Where(p => p.客戶Id == 客戶資料.Id).ToList();
            ViewBag.Contact = RepositoryHelper.Get客戶聯絡人Repository().All().Where(p => p.客戶Id == 客戶資料.Id).ToList();
            return View(客戶資料);
        }

        // GET: Custom/Delete/5
        [IDFilter]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            客戶資料 客戶資料 = CustomRepos.Find(p => p.Id == id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: Custom/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [IDFilter]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶資料 客戶資料 = CustomRepos.Find(p => p.Id == id);
            //db.客戶資料.Remove(客戶資料);
            //db.SaveChanges();
            CustomRepos.Delete(客戶資料);
            CustomRepos.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteBank(int? id,int? cid)
        {

            客戶銀行資訊Repository repo = RepositoryHelper.Get客戶銀行資訊Repository();
            var e = repo.Find(p => p.Id == id);
            repo.Delete(e);

            return RedirectToAction("Details", new { id = cid });
        }
        public ActionResult DeleteContact(int? id, int? cid)
        {
            客戶聯絡人Repository repo = RepositoryHelper.Get客戶聯絡人Repository();
            var e = repo.Find(p => p.Id == id);
            repo.Delete(e);
            return RedirectToAction("Details", new { id = cid });

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBatch(BatchUpdateViewModel form)
        {
            //TODO Model繫結時未觸發模型驗證，而在執行更新方法時觸發
            if (this.ModelState.IsValid)
            {
                var _bankrepo = RepositoryHelper.Get客戶銀行資訊Repository();
                var _contactrepo = RepositoryHelper.Get客戶聯絡人Repository();
                foreach (var item in form.bank)
                {
                    var e = _bankrepo.Find(p => p.Id == item.Id);
                    e.帳戶號碼 = item.帳戶號碼;
                    _bankrepo.Edit(e);
                }
                foreach (var item in form.contact)
                {
                    var e = _contactrepo.Find(p => p.Id == item.Id);
                    e.電話 = item.電話;
                    _contactrepo.Edit(e);
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult Export()
        {
            using (ExcelPackage p = new ExcelPackage())
            {
                ExcelWorksheet sheet = p.Workbook.Worksheets.Add("客戶資料");
                sheet.Cells[1, 1].Value = "客戶名稱";
                sheet.Cells[1, 2].Value = "統一編號";
                sheet.Cells[1, 3].Value = "電話";
                sheet.Cells[1, 4].Value = "傳真";
                sheet.Cells[1, 5].Value = "地址";
                sheet.Cells[1, 6].Value = "Email";
                int row = 2;
                var custom = CustomRepos.All();
                foreach (var item in custom)
                {
                    sheet.Cells[row, 1].Value = item.客戶名稱;
                    sheet.Cells[row, 2].Value = item.統一編號;
                    sheet.Cells[row, 3].Value = item.電話;
                    sheet.Cells[row, 4].Value = item.傳真;
                    sheet.Cells[row, 5].Value = item.地址;
                    sheet.Cells[row, 6].Value = item.Email;
                    row++;
                }
                
                return File(p.GetAsByteArray(), "application/vnd.ms-excel",string.Format( "{0}_客戶資料匯出.xlsx",DateTime.Now.ToString("yyyyMMdd")));
            }
            
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
             //   db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_Week2_HK/Views/Custom/Create.cshtml
@model MVC_Week1_HK.Models.客戶資料

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_Week2_HK/Views/Custom/Delete.cshtml
@model MVC_Week1_HK.Models.客戶資料

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC_Week2_HK/Views/Custom/Details.cshtml
@model MVC_Week1_HK.Models.客戶資料
@using MVC_Week1_HK.Models;
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<h4>客戶銀行資訊</h4>
@{
    var bank = ViewBag.Bank as List<客戶銀行資訊>;
    var contact = ViewBag.Contact as List<客戶聯絡人>;
}
<table class="table">
    <tr>
        <th>
            銀行名稱
        </th>
        <th>
            銀行代碼
        </th>
        <th>
            分行代碼
        </th>
        <th>
            帳戶名稱
        </th>
        <th>
            帳戶號碼
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in bank)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.銀行名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.銀行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.分行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶號碼)
            </td>
            
            <td>
                @Html.ActionLink("Delete", "DeleteBank", new { id = item.Id, cid = Model.Id }, new { onclick = "return confirm('確定刪除此資料')" })
            </td>
        </tr>
    }

</table>
<h4>客戶聯絡人</h4>
<table class="table">
    <tr>
        <th>
            職稱
        </th>
        <th>
            姓名
        </th>
        <th>
            Email
        </th>
        <th>
            手機
        </th>
        <th>
            電話
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in contact)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.職稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.姓名)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.手機)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.電話)
            </td>
          
            <td>
                @Html.ActionLink("Delete", "DeleteContact", new { id = item.Id, cid = Model.Id }, new { onclick = "return confirm('確定刪除此資料')" })
            </td>
        </tr>
    }

</table>

MVC_Week2_HK/Views/Custom/Edit.cshtml
@model MVC_Week1_HK.Models.客戶資料

@{
    ViewBag.Title = "Edit";
    var bank = (ViewBag.Bank as List<MVC_Week1_HK.Models.客戶銀行資訊>).ToArray();
    var contact = (ViewBag.Contact as List<MVC_Week1_HK.Models.客戶聯絡人>).ToArray();
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>

  
}
@using (Html.BeginForm("UpdateBatch", "Custom"))
{
    @Html.AntiForgeryToken()
    <input type="submit" value="批次更新" />
    
    <h4>客戶銀行資訊</h4>
    <table class="table">
        <tr>
            <th>
                銀行名稱
            </th>
            <th>
                銀行代碼
            </th>
            <th>
                分行代碼
            </th>
            <th>
                帳戶名稱
            </th>
            <th>
                帳戶號碼
            </th>

        </tr>

        @for (var i = 0; i < bank.Length; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => bank[i].銀行名稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => bank[i].銀行代碼)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => bank[i].分行代碼)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => bank[i].帳戶名稱)
                </td>
                <td>
                    @Html.EditorFor(modelItem => bank[i].帳戶號碼)
                </td>
                @Html.HiddenFor(modelItem => bank[i].Id);

            </tr>
        }

    </table>
    <h4>客戶聯絡人</h4>
    <table class="table">
        <tr>
            <th>
                職稱
            </th>
            <th>
                姓名
            </th>
            <th>
                Email
            </th>
            <th>
                手機
            </th>
            <th>
                電話
            </th>

        </tr>

        @for (var i = 0; i < contact.Length; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => contact[i].職稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact[i].姓名)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact[i].Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact[i].手機)
                </td>
                <td>
                    @Html.EditorFor(modelItem => contact[i].電話)
                </td>
                @Html.HiddenFor(modelItem => contact[i].Id);

            </tr>
        }

    </table>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_Week2_HK/Views/Custom/Index.cshtml
@model IEnumerable<MVC_Week1_HK.Models.客戶資料>

@{
    ViewBag.Title = "Index";
}

<h2>客戶資料管理</h2>

<p>
    @Html.ActionLink("Create New", "Create") | @Html.ActionLink("Export", "Export") 
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.統一編號)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.電話)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.傳真)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.地址)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.統一編號)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.傳真)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.地址)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>